/** The three locales the landing page ships. */
export const LANGS = ["zh-TW", "zh-CN", "en"] as const;

export type Lang = (typeof LANGS)[number];

export type MessageKey =
  | "description"
  | "tagline"
  | "docsCta"
  | "installLabel"
  | "requiresNote"
  | "copy"
  | "copied"
  | "factsTitle"
  | "factNativeLabel"
  | "factNativeText"
  | "factStdlibLabel"
  | "factStdlibText"
  | "factLombokLabel"
  | "factLombokText"
  | "factWebLabel"
  | "factWebText"
  | "factJsonLabel"
  | "factJsonText"
  | "factGcLabel"
  | "factGcText"
  | "footerDocs"
  | "footerGithub"
  | "themeLabel"
  | "langLabel";

export type Messages = Readonly<Record<MessageKey, string>>;

/** Native names: the language control reads the same whichever locale is active. */
export const LANG_LABELS: Readonly<Record<Lang, string>> = {
  "zh-TW": "繁體中文",
  "zh-CN": "简体中文",
  en: "English",
};

/** Value for `og:locale`. */
export const LANG_OG_LOCALES: Readonly<Record<Lang, string>> = {
  "zh-TW": "zh_TW",
  "zh-CN": "zh_CN",
  en: "en_US",
};

/** Shown in the footer; a command, so it is identical in every locale. */
export const INSTALL_COMMAND = "go install github.com/teyru-lang/Teyru/cmd/teyru@latest";

const zhTW: Messages = {
  description:
    "Teyru 是一門 Java 形狀的程式語言，直接編譯成原生執行檔：.teyru 原始碼經由 Go 編譯器與 C 交給 clang/LLVM。沒有 JVM，沒有 bytecode。",
  tagline: "Java 形狀的語言，直接編譯成原生執行檔。沒有 JVM，沒有 bytecode。",
  docsCta: "閱讀文件",
  installLabel: "安裝編譯器",
  requiresNote: "需要 Go，以及 clang 或 gcc。",
  copy: "複製",
  copied: "已複製",
  factsTitle: "它是什麼",
  factNativeLabel: "原生執行檔",
  factNativeText: "經由 Go 前端、產生的 C 與 clang/LLVM，編成原生執行檔——沒有 JVM，沒有 bytecode。",
  factStdlibLabel: "標準程式庫",
  factStdlibText: "以 Teyru 本身撰寫，與每個程式一起編譯與檢查。",
  factLombokLabel: "標註",
  factLombokText: "相容 Lombok，在語意分析階段展開成一般的成員。",
  factWebLabel: "Web 框架",
  factWebText: "Spring 形狀的容器與 web 層，路由在編譯期產生。",
  factJsonLabel: "JSON 綁定",
  factJsonText: "Gson 形狀，物件綁定由編譯器產生。",
  factGcLabel: "垃圾回收",
  factGcText: "C 執行期的保守式標記清除回收器，沒有任何虛擬機。",
  footerDocs: "文件",
  footerGithub: "GitHub",
  themeLabel: "切換淺色與深色主題",
  langLabel: "語言",
};

const zhCN: Messages = {
  description:
    "Teyru 是一门 Java 形状的编程语言，直接编译成原生可执行文件：.teyru 源码经由 Go 编译器与 C 交给 clang/LLVM。没有 JVM，没有字节码。",
  tagline: "Java 形状的语言，直接编译成原生可执行文件。没有 JVM，没有字节码。",
  docsCta: "阅读文档",
  installLabel: "安装编译器",
  requiresNote: "需要 Go，以及 clang 或 gcc。",
  copy: "复制",
  copied: "已复制",
  factsTitle: "它是什么",
  factNativeLabel: "原生可执行文件",
  factNativeText: "经由 Go 前端、生成的 C 与 clang/LLVM，编译成原生可执行文件——没有 JVM，没有字节码。",
  factStdlibLabel: "标准库",
  factStdlibText: "用 Teyru 本身编写，与每个程序一起编译与检查。",
  factLombokLabel: "注解",
  factLombokText: "兼容 Lombok，在语义分析阶段展开成普通的成员。",
  factWebLabel: "Web 框架",
  factWebText: "Spring 形状的容器与 web 层，路由在编译期生成。",
  factJsonLabel: "JSON 绑定",
  factJsonText: "Gson 形状，对象绑定由编译器生成。",
  factGcLabel: "垃圾回收",
  factGcText: "C 运行时的保守式标记清除回收器，没有任何虚拟机。",
  footerDocs: "文档",
  footerGithub: "GitHub",
  themeLabel: "切换浅色与深色主题",
  langLabel: "语言",
};

const en: Messages = {
  description:
    "Teyru is a language in the shape of Java that compiles straight to a native executable. No JVM, no bytecode.",
  tagline: "A Java-shaped language that compiles to a native binary. No JVM, no bytecode.",
  docsCta: "Read the documentation",
  installLabel: "Install the compiler",
  requiresNote: "Requires Go and clang or gcc.",
  copy: "Copy",
  copied: "Copied",
  factsTitle: "What it is",
  factNativeLabel: "Native binary",
  factNativeText:
    "Compiled through a Go front end, generated C and clang/LLVM into a native executable — no JVM, no bytecode.",
  factStdlibLabel: "Standard library",
  factStdlibText: "Written in Teyru itself, and compiled and checked together with every program.",
  factLombokLabel: "Annotations",
  factLombokText: "Lombok-compatible, expanded into ordinary members during semantic analysis.",
  factWebLabel: "Web framework",
  factWebText: "A Spring-shaped container and web layer, with the routes compiled.",
  factJsonLabel: "JSON binding",
  factJsonText: "Gson-shaped, with the object binding generated by the compiler.",
  factGcLabel: "Garbage collector",
  factGcText: "A C runtime with a conservative mark-and-sweep collector and no virtual machine.",
  footerDocs: "Documentation",
  footerGithub: "GitHub",
  themeLabel: "Switch between the light and dark theme",
  langLabel: "Language",
};

export const MESSAGES: Readonly<Record<Lang, Messages>> = {
  "zh-TW": zhTW,
  "zh-CN": zhCN,
  en,
};

export const MESSAGE_KEYS: readonly MessageKey[] = Object.keys(en) as MessageKey[];

export function isLang(value: string): value is Lang {
  return (LANGS as readonly string[]).includes(value);
}

export function isMessageKey(value: string): value is MessageKey {
  return (MESSAGE_KEYS as readonly string[]).includes(value);
}

const STORAGE_KEY = "teyru:lang";

export function storedLang(): Lang | null {
  try {
    const value = window.localStorage.getItem(STORAGE_KEY);
    return value !== null && isLang(value) ? value : null;
  } catch (error) {
    return null;
  }
}

export function persistLang(lang: Lang): void {
  try {
    window.localStorage.setItem(STORAGE_KEY, lang);
  } catch (error) {
    // Storage disabled: the choice simply does not survive the visit.
  }
}

/**
 * Picks a locale from an Accept-Language-shaped preference list, in order.
 * Traditional Chinese wins for a bare `zh` because it is the source language.
 */
export function detectLang(languages: readonly string[]): Lang {
  let sawBareChinese = false;
  for (const raw of languages) {
    const tag = raw.toLowerCase();
    if (tag === "zh" || tag.startsWith("zh-")) {
      if (/(hant|-tw|-hk|-mo)/.test(tag)) {
        return "zh-TW";
      }
      if (/(hans|-cn|-sg)/.test(tag)) {
        return "zh-CN";
      }
      sawBareChinese = true;
      continue;
    }
    if (tag === "en" || tag.startsWith("en-")) {
      return "en";
    }
  }
  return sawBareChinese ? "zh-TW" : "en";
}
